project:
  type: website
  output-dir: docs
website:
  title: "dongho-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: 깃헙
        href: https://github.com/qkrehdgh21/dongho-blog
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
